src/agente/agente/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from core.views import PropertyDetailView, PropertyCreate, UserPropertyList
from core.models import Property

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', UserPropertyList.as_view(template_name='property_list.html'), name='home'),
    #url(r'^$', 'core.views.home', name='home'),
    url(r'^search', 'core.views.home', name='search'),
    url(r'^results', 'core.views.results', name='search-results'),
    url(r'^contactar$', 'core.views.contactar', name='contactar'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'home.html'}, name='logout'),

    url(r'^property/(?P<pk>\d+)$', PropertyDetailView.as_view(template_name='property_detail.html'), name='property-detail'),
    url(r'^property/add$', PropertyCreate.as_view(template_name='property_form.html'), name='property-add'),
    url(r'^property/list$', UserPropertyList.as_view(template_name='property_list.html'), name='property-list'),
    # url(r'^agente/', include('agente.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/agente/core/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User, UserManager, AbstractBaseUser

from django.core.urlresolvers import get_script_prefix, reverse
from django.conf import settings

def join_absolute_url(*st_path):
    """ Join path html"""
    if len(st_path)>0 and "http" in st_path[0]:
        base_url=st_path[0].strip("/")
        st_path=st_path[1:]
    else:
        base_url=get_script_prefix().strip("/")
        
    return '/'.join([base_url] + [i.strip("/") for i in st_path])


def get_absolute_url(*st_path):
    return join_absolute_url(settings.MEDIA_URL,*st_path)


class MyUserManager(UserManager):

    def create_user(self, username, email, password=None):
        user = self.model(email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        user = self.create_user(username, '', password)
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    
    def with_available_properties(self, query):
        zone = query.get('zone')
        sector = query.get('sector')
        social_bedrooms = query.get('social-bedrooms')
        service_bedrooms = query.get('service-bedrooms')
        social_bathrooms = query.get('social-bathrooms')
        service_bathrooms = query.get('service-bathrooms')
        parking_spaces = query.get('parking-spaces')
        parking_type = query.get('parking-type')
        area = query.get('area')
        administrative_fee = query.get('administrative-fee')
        antiquity = query.get('antiquity')
        price = query.get('price')
        duplex = query.get('duplex')
        penthouse = query.get('penthouse')
        study_room = query.get('study-room')

        records = Property.objects.all()
        if zone:
            records = records.filter(zone=zone)
        if sector:
            records = records.filter(sector=sector)
        if social_bedrooms:
            records = records.filter(social_bedrooms=social_bedrooms)
        if service_bedrooms:
            records = records.filter(service_bedrooms=service_bedrooms)
        if social_bathrooms:
            records = records.filter(social_bathrooms=social_bathrooms)
        if service_bathrooms:
            records = records.filter(service_bathrooms=service_bathrooms)
        if parking_spaces:
            records = records.filter(parking_spaces=parking_spaces)
        if parking_type:
            records = records.filter(parking_type=parking_type)
        if area:
            records = records.filter(area=area)
        if administrative_fee:
            records = records.filter(administrative_fee=administrative_fee)
        if antiquity:
            records = records.filter(antiquity=antiquity)
        if price:
            records = records.filter(price=price)
        if duplex:
            records = records.filter(duplex=duplex)
        if penthouse:
            records = records.filter(penthouse=penthouse)
        if study_room:
            records = records.filter(study_room=study_room)

        managers = {}
        id = -1
        for property in records:
            id = property.manager.id
            if id not in managers:
                managers[id] = property.manager
                managers[id].found_properties = []
            
            managers[id].found_properties.append(property.id)

        results = []
        for manager in managers:
            results.append(managers[manager])

        return results


class User(AbstractBaseUser):
    email = models.EmailField(unique=True)
    names = models.CharField(max_length=32)
    last_names = models.CharField(max_length=32)
    phone = models.CharField(max_length=15)
    pic = models.ImageField(upload_to='users/', blank=True)
    cc = models.CharField(max_length=20)

    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def is_staff(self):
        return True

    def has_module_perms(self, app_label):
        print app_label
        return True

    def has_perm(self, perm, obj=None):
        print '-------'
        print '%s %s' % (perm, obj) 
        print '-------'
        return True

    def get_short_name(self):
        return self.names

    def get_username(self):
        return self.names

    @property
    def image_url(self):
        return get_absolute_url(self.pic.name)


    def full_name(self):
        return u'%s %s' % (self.names, self.last_names)

    def __unicode__(self):
        return self.full_name()


TYPE_PROPERTY_CHOICES = (('ap','Apartamento'),
                         ('ca','Casa'),
                         ('of','Oficina'),
                         ('bo','Bodega'))

ZONE_PROPERTY_CHOICES = (('N', 'Norte'),
                         ('No', 'Noroccidente'),
                         ('O', 'Occidental'),
                         ('C', 'Chapinero'),
                         ('G', 'Guaymaral'),
                         ('C', 'Centro'),
                         ('S', 'Sur'))

PARKING_TYPES = (('I', 'Independiente'),
                 ('S', 'En servidumbre'))

class Property(models.Model):
    manager = models.ForeignKey(User, verbose_name='Agente')
    property_type = models.CharField(max_length=2, verbose_name='Tipo de Propiedad', choices=TYPE_PROPERTY_CHOICES)
    zone = models.CharField(max_length=2, verbose_name='Zona', choices=ZONE_PROPERTY_CHOICES)
    sector = models.CharField(max_length=500, verbose_name='Sector')
    social_bedrooms = models.IntegerField(verbose_name='Alcobas')
    service_bedrooms = models.IntegerField(verbose_name='Alcobas de Servicio')
    social_bathrooms = models.IntegerField(verbose_name='Baños sociales')
    service_bathrooms = models.IntegerField(verbose_name='Baños de Servicio')
    parking_spaces = models.IntegerField(verbose_name='Parqueaderos')
    parking_type = models.CharField(max_length=1, verbose_name='Tipo de parqueadero', choices=PARKING_TYPES)
    area = models.IntegerField(verbose_name='Área')
    administrative_fee = models.BigIntegerField(verbose_name='Administración')
    antiquity = models.IntegerField(verbose_name='Antigüedad')
    price = models.BigIntegerField(verbose_name='Precio')
    duplex = models.BooleanField(default=False, verbose_name='Duplex')
    penthouse = models.BooleanField(default=False, verbose_name='Penthouse')
    study_room = models.BooleanField(default=False, verbose_name='Cuarto de estudio')
    extra_info = models.TextField(blank=True, verbose_name='Información Adicional')
    address = models.CharField(max_length=500, verbose_name='Direccion')

    def __unicode__(self):
        return u'%s en %s. valor: %s' % (self.property_type, self.sector, self.price)

    def get_absolute_url(self):
        return reverse('property-detail', kwargs={'pk': self.pk})

class PropertyDictionaryManager(models.Manager):
    def get_all_names(self):
        return self.all()

class PropertyDictionary(models.Model):
    name = models.CharField(max_length=500, verbose_name='Nombre')
    value = models.CharField(max_length=500, verbose_name='Valor')
    clean_name = models.CharField(max_length=500)
    clean_value = models.CharField(max_length=500)
    the_property = models.ForeignKey(Property, related_name='value_dictionary')
    objects = PropertyDictionaryManager()

    def __unicode__(self):
        return u'%s: %s' % (self.name, self.value)

src/agente/core/views.py
from django.shortcuts import render_to_response, redirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.http import Http404

from core.models import Property, PropertyDictionary
import urllib

from models import User

def home(request):
    if request.method == 'POST':
        return redirect('/results?%s' % request.POST.urlencode())

    properties_dictionary = PropertyDictionary.objects.get_all_names()
    return render_to_response('home.html',
            {'properties_dictionary': properties_dictionary},
            context_instance=RequestContext(request))

def results(request):
    results = User.objects.with_available_properties(request.GET)

    return render_to_response('results.html', {'contacts': results},
            context_instance=RequestContext(request))


class UserPropertyList(ListView):
    model = Property

    def get_queryset(self):
        return self.request.user.property_set.all()

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserPropertyList, self).dispatch(*args, **kwargs)


class PropertyCreate(CreateView):
    model = Property
    fields = ['name']

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PropertyCreate, self).dispatch(*args, **kwargs)


class PropertyDetailView(DetailView):
    model = Property

    def get_object(self, queryset=None):
        try:
            return self.request.user.property_set.get(pk=self.kwargs['pk'])
        except Property.DoesNotExist:
            raise Http404


    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PropertyDetailView, self).dispatch(*args, **kwargs)

def contactar(request):
    contact_ids = request.POST.getlist('contact')
    return redirect('search')

src/agente/core/templates/home.html
{% extends "layout.html" %}
{% block container %}
<form method="post" action="">
    {% csrf_token %}
    <ul>
        {% for key in properties_dictionary %}
        <li>
            <label for="{{ key.clean_name }}">{{ key.name  }}</label>
            <input name="{{ key.clean_name }}" id="{{ key.clean_name }}"></input>
        </li>
        {% endfor %}
        <li>
            <label for="id_zone">Zona</label>
            <select id="id_zone" name="zone">
                <option value="" selected="selected">Todas las Zonas</option>
                <option value="N">Norte</option>
                <option value="No">Noroccidente</option>
                <option value="O">Occidental</option>
                <option value="C">Chapinero</option>
                <option value="G">Guaymaral</option>
                <option value="C">Centro</option>
                <option value="S">Sur</option>
            </select>
        </li>
        <li>
            <label for="sector">Sector</label>
            <input name="sector" id="sector"></input>
        </li>
        <li>
            <label for="social-bedrooms">Alcobas</label>
            <select id="social-bedrooms" name="social-bedrooms">
                <option value=''>No importa</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
        </li>
        <li>
            <label for="service-bedrooms">Alcobas de servicio</label>
            <select id="service-bedrooms" name="service-bedrooms">
                <option value=''>No importa</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
        </li>
        <li>
            <label for="social-bathrooms">Baños sociales</label>
            <select id="social-bathrooms" name="social-bathrooms">
                <option value=''>No importa</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
        </li>
        <li>
            <label for="service-bathrooms">Baños de servicio</label>
            <select id="service-bathrooms" name="service-bathrooms">
                <option value=''>No importa</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
        </li>
        <li>
            <label for="parking-spaces">Parqueaderos</label>
            <select id="parking-spaces" name="parking-spaces">
                <option value=''>No importa</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
        </li>
        <li>
            <label for="parking-type">Tipo de Parqueadero</label>
            <select id="parking-type" name="parking-type">
                <option value="" selected="selected">No importa</option>
                <option value="I">Independiente</option>
                <option value="S">En servidumbre</option>
            </select>
        </li>
        <li>
            <label for="area">Área</label>
            <input id="area" name="area"></input>
        </li>
        <li>
            <label for="administrative-fee">Administracion</label>
            <input id="administrative-fee" name="administrative-fee"></input>
        </li>
        <li>
            <label for="antiquity">Antiguedad</label>
            <input id="antiquity" name="antiquity"></input>
        </li>
        <li>
            <label for="price">Precio</label>
            <input id="price" name="price"></input>
        </li>
        <li>
            <label for="duplex">Duplex</label>
            <select id="duplex" name="duplex">
                <option value="">No importa</option>
                <option value="1">Si</option>
                <option value="0">No</option>
            </select>
        </li>
        <li>
            <label for="penthouse">Penthouse</label>
            <select id="penthouse" name="penthouse">
                <option value="">No importa</option>
                <option value="1">Si</option>
                <option value="0">No</option>
            </select>
        </li>
        <li>
            <label for="study-room">Con cuarto de estudio</label>
            <select id="study-room" name="study-room">
                <option value="">No importa</option>
                <option value="1">Si</option>
                <option value="0">No</option>
            </select>
        </li>
    </ul>
    <input type="submit" value="Enviar"/>
</form>
{% endblock %}

src/agente/core/templates/layout.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, maximum-scale = 1, minimum-scale=1">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
    {% block extra_head %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'home' %}"
                    class="back">Inicio</a></li>
                <li><a href="{% url 'search' %}"
                    class="back">Buscar</a></li>
                <li><a href="{% url 'logout' %}"
                    class="logout">Salir</a></li>
                {% else %}
                <li><a href="{% url 'login' %}"
                    class="login">Iniciar sesi&oacute;n</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <section class="container">
        {% block container %}{% endblock %}
    </section>
</body>
</html>

src/agente/core/templates/login.html
{% extends "layout.html" %}

{% block container %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

src/agente/core/templates/property_detail.html
{% extends "layout.html" %}
{% block container %}
    <table>
        <tr>
            <td>Zona: </td>
            <td>{{object.zone}}</td>
        </tr>
        <tr>
            <td>Sector: </td>
            <td>{{object.sector}}</td>
        </tr>
        <tr>
            <td>Alcobas: </td>
            <td>{{object.social_bedrooms}}</td>
        </tr>
        <tr>
            <td>Alcobas de servicio</td>
            <td>{{object.service_bedrooms}}</td>
        </tr>
        <tr>
            <td>Baños sociales: </td>
            <td>{{object.social_bathrooms}}</td>
        </tr>
        <tr>
            <td>Baños de servicio</td>
            <td>{{object.service_bathtrooms}}</td>
        </tr>
        <tr>
            <td>Parqueaderos: </td>
            <td>{{object.parking_spaces}}</td>
        </tr>
        <tr>
            <td>Tipo de Parqueadero: </td>
            <td>{{object.parking_type}}</td>
        </tr>
        <tr>
            <td>Área: </td>
            <td>{{object.area}}</td>
        </tr>
        <tr>
            <td>Administración: </td>
            <td>{{object.administrative_fee}}</td>
        </tr>
        <tr>
            <td>Antigüedad: </td>
            <td>{{object.antiquity}}</td>
        </tr>
        <tr>
            <td>Precio: </td>
            <td>{{object.price}}</td>
        </tr>
        <tr>
            <td>Duplex: </td>
            <td>{{object.duplex}}</td>
        </tr>
        <tr>
            <td>Penthouse: </td>
            <td>{{object.penthouse}}</td>
        </tr>
        <tr>
            <td>Cuarto de Estudio: </td>
            <td>{{object.study_room}}</td>
        </tr>
        <tr>
            <td>Información Extra: </td>
            <td>{{object.extra_info}}</td>
        </tr>
    </table>
{% endblock %}

src/agente/core/templates/property_form.html
{% extends "layout.html" %}
{% block container %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
{% endblock %}

src/agente/core/templates/property_list.html
{% extends "layout.html" %}

{% block container %}
    <h2>Mis Propiedades</h2>
    <a href="{% url 'property-add' %}">Agregar Nueva Propiedad</a>
    <hr>
    <ul>
        {% for property in object_list %}
            <li><a href="{% url 'property-detail' pk=property.id %}">{{ property }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

src/agente/core/templates/results.html
{% extends "layout.html" %}
{% block container %}
<form method="post" action="/contactar">
    {% csrf_token %}
    <ol>
        {% for contact in contacts %}
        <li class="contact-card">
            <img class="avatar" src='{{ contact.image_url }}'>
            <div class="contact">
                <ol>
                    <li>{{ contact.full_name }}</li>
                    <li>Propiedades encontradas {{ contact.found_properties|length }}</li>
                    <li>Reputacion +10/-3</li>
                    <li>
                        <a href="#" class="select-contact"
                          data-select-this-contact="{{ contact.id }}"
                          onclick="return select_contact(this);">Seleccionar</a>
                        <input type="hidden" class="check-contact"
                          name="contact" id="{{ contact.id }}"/>
                    </li>
                </ol>
            </div>
        </li>
        {% endfor %}
    </ol>
    <input type="submit" value="Contactar seleccionados"/>
</form>
<script>
    function select_contact(element) {
      var id = element.getAttribute('data-select-this-contact');
      var check_contact = document.getElementById(id);

      if(!check_contact.value) {
        element.className += " contact-selected";
        element.innerText = "Seleccionado";
        check_contact.value = id;
      } else {
        element.className = element.className.replace(" contact-selected", "");
        element.innerText = "Seleccionar";
        check_contact.value = null;
      }

      return false;
    }
</script>
{% endblock %}